import userModel from "./user.js";
import tokenModel from "./token.js";
import logModel from "./log.js";
import courseModel from "./course.js";
import techNewsModel from "./technews.js";
import updateModel from "./update.js";
import tudoModel from "./todo.js";
import moduleModel from "./module.js";
import coursePrerequisiteModel from "./coursePrerequisite.js";
import aboutEducatorModel from "./aboutEducator.js";
import assignmentModel from "./assignment.js";
import courseTestimonialModel from "./courseTestimonial.js";
import passingCriteriaModel from "./passingCriteria.js";
import enrollCoursesModel from "./enrollCourses.js";
import educatorRatingModel from "./educatorRating.js";
import notificationModel from "./notification.js";
import badgeModel from "./badge.js";
import CourseRatingModel from "./CourseRating.js";

export const User = userModel;
export const Token = tokenModel;
export const Log = logModel;
export const Course = courseModel;
export const techNews = techNewsModel;
export const update = updateModel;
export const Todo = tudoModel;
export const Module = moduleModel;
export const CoursePrerequisite = coursePrerequisiteModel;
export const AboutEducator = aboutEducatorModel;
export const Assignment = assignmentModel;
export const CourseTestimonial = courseTestimonialModel;
export const PassingCriteria = passingCriteriaModel;
export const EnrollCourse = enrollCoursesModel;
export const EducatorRating = educatorRatingModel;
export const Notification = notificationModel;
export const Badge = badgeModel;
export const CourseRating = CourseRatingModel;
